### ISSUE TITLE
Swagger Integration

### ISSUE THREAD

**Issue by Akinnagbe** [bradwellsb/blazor-contacts#1]
Please is there swagger integration for the OData API.

thanks

**Comment by bradwellsb** [comment]
As of [v7.4.0 with Endpoint Routing](https://devblogs.microsoft.com/odata/enabling-endpoint-routing-in-odata/), OData now supports Swagger integration. Here's an example: [https://github.com/hassanhabib/OData3.1WithSwagger](https://github.com/hassanhabib/OData3.1WithSwagger)
